### ISSUE TITLE
need component that truncates string and adds copy button next to it

### ISSUE THREAD

**Issue by ChristianChiarulli** [nodetec/notebin#59]
like

npub...60k2 [copybutton]

**Comment by umop3plsdn** [comment]
the copy feature on this only copies "npub...y6kf" currently and not the full key

**Comment by MAHcodes** [comment]
you're right, should be fixed [here](https://github.com/nodetec/notebin/commit/b05fe2b82b737cb6eb603f70d697ea99c435949c), thanks @umop3plsdn!
