### ISSUE TITLE
fix width issue on profile

### ISSUE THREAD

**Issue by ChristianChiarulli** [nodetec/notebin#95]
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/29136904/213740952-a4cd1aad-50bb-4836-8ffe-8d7741b3ccbc.png">

**Comment by MAHcodes** [comment]
I pushed the fix, hopefully it worked, can you check?

**Comment by ChristianChiarulli** [comment]
@MAHcodes seems to be back

**Comment by MAHcodes** [comment]
😬 try now

**Comment by ChristianChiarulli** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/29136904/213830871-fc6def4e-2bef-48e0-954f-8a0634ff3a0f.png">

Brave is being difficult

**Comment by MAHcodes** [comment]
https://user-images.githubusercontent.com/69465962/213868042-6437d55b-c575-42dd-a2e2-a8724eecc317.mp4

I pushed the fix, but there's something weird, with the title is centered and there's no padding around the div containing notes and profile, this is how it behaves on my screen (1920x1080), try clearing site cache, let me know if the fix doesn't work for you.
